### ISSUE TITLE
.Site.Social was deprecated

### ISSUE THREAD

**Issue by Signum** [ashishb/wp2hugo#71] opened 2024-10-17 13:19 UTC
I just tried to update my Wordpress website to Hugo but I am stuck here:

03:13:22PM DBG hugo_gen_setup.go:180 > Running Hugo setup commands

03:13:23PM ERR hugo_gen_setup.go:187 > error running Hugo setup commands error="exit status 1" cmd="hugo version && cd /tmp && hugo new site generated-2024-10-17-15-13-22 --format yaml && cd generated-2024-10-17-15-13-22 && git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1 && rm -rf themes/PaperMod/.git themes/PaperMod/.github && echo \"theme: 'PaperMod'\">> hugo.yaml && hugo" output="hugo v0.136.1-64d1865c1e21c66feb96ffedda44a9eba2365af9 linux/amd64 BuildDate=2024-10-16T16:05:18Z VendorInfo=gohugoio\nCongratulations! Your new Hugo site was created in /tmp/generated-2024-10-17-15-13-22.\n\nJust a few more steps...\n\n1. Change the current directory to /tmp/generated-2024-10-17-15-13-22.\n2. Create or install a theme:\n   - Create a new theme with the command \"hugo new theme <THEMENAME>\"\n   - Or, install a theme from https://themes.gohugo.io/\n3. Edit hugo.yaml, setting the \"theme\" property to the theme name.\n4. Create new content with the command \"hugo new content <SECTIONNAME>/<FILENAME>.<FORMAT>\".\n5. Start the embedded web server with the command \"hugo server --buildDrafts\".\n\nSee documentation at https://gohugo.io/.\nStart building sites … \nhugo v0.136.1-64d1865c1e21c66feb96ffedda44a9eba2365af9 linux/amd64 BuildDate=2024-10-16T16:05:18Z VendorInfo=gohugoio\n\n**ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'social' or use .Site.Params.Social instead.\nTotal in 23 ms\nError: error building site: logged 1 error(s)\n"**

03:13:23PM FTL main.go:43 > Error: error running Hugo setup commands: exit status 1

I only have basic Hugo knowledge so I'm not sure where to look. Checking other search engine results it points to a problem with the PaperMod theme that creates tags that are not supported by 0.136.1. Because someone else knows better.

**Comment by ashishb** [comment] 2024-10-21 06:36
@Signum the issue is with `03:13:23PM FTL main.go:43 > Error: error running Hugo setup commands: exit status 1`

**Comment by ashishb** [comment] 2024-10-21 06:37
Duplicate of https://github.com/ashishb/wp2hugo/issues/70

**Closed by ashishb** 2024-10-21 06:37 UTC

**Comment by astralbodies** [comment] 2024-10-27 21:14
Is this actually a duplicate of #70, @ashishb? I built from source and am still getting the `exit status 1` error. The issue you linked to mentions error 127.

**Comment by habi** [comment] 2024-10-29 14:13
I also see this issue.
I've built `wp2hugo` from source (https://github.com/ashishb/wp2hugo/commit/cb78882) and get

````go
03:10:34PM DBG hugo_gen_setup.go:185 > Running Hugo setup command cmd="cd habignach/generated-2024-10-29-15-10-33 && hugo" step=7 totalSteps=7
03:10:34PM ERR hugo_gen_setup.go:192 > error running Hugo setup command error="exit status 1" cmd="cd habignach/generated-2024-10-29-15-10-33 && hugo" output="Start building sites … \nhugo v0.136.5-46cccb021bc6425455f4eec093f5cc4a32f1d12c linux/amd64 BuildDate=2024-10-24T12:26:27Z VendorInfo=gohugoio\n\nERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'social' or use .Site.Params.Social instead.\nTotal in 60 ms\nError: error building site: logged 1 error(s)\n"
03:10:34PM FTL main.go:43 > Error: error running Hugo setup command 'cd habignach/generated-2024-10-29-15-10-33 && hugo' -> exit status 1
````

If it helps, my .xml file is available here: https://github.com/habi/blog/blob/main/habignach.WordPress.2024-10-29.xml

**Comment by enricomingardo** [comment] 2024-10-30 14:04
I also have the same issue with exit code 1 (not 127). 
It seems to me that the problem is related to the command `cd /tmp/generated-2024-10-30-14-58-00 && hugo` that states clearly:
`ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'social' or use .Site.Params.Social instead`

**Comment by enricomingardo** [comment] 2024-10-30 14:48
> I also have the same issue with exit code 1 (not 127). It seems to me that the problem is related to the command `cd /tmp/generated-2024-10-30-14-58-00 && hugo` that states clearly: `ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'social' or use .Site.Params.Social instead`

probably related to  https://github.com/adityatelange/hugo-PaperMod/issues/1573

**Comment by habi** [comment] 2024-11-12 16:18
Not an issue anymore for me with #fce9e2d
